### ISSUE TITLE
Devices reporting (X GB - few MB) will report X/2 GB device-ram value

### ISSUE THREAD

**Issue by fmeawad** [WICG/device-ram#1]
On Linux specifically, the OS reports the amount of physical memory as a value that is a few (hundred) MB less than the advertised number. By ceiling the number down, we get X/2 of the available memory.

For example, a linux machine with 64GB memory, the system will report the physical memory as 64385MB, which is ~62.9GB.

Based on the calculations in the spec, the system reported memory will be 32GB. The gap between the reported number and the actual number is large (~2X in most cases).
Ideas:
- Instead of rounding down to the closest power of 2, we might find the closest power of 2 instead, if it is in the middle use the lower value.
- Increase the granularity by using the most significant 2 bits instead of just 1 (in this example, it would report 48GB)

**Comment by spanicker** [comment]
SGTM: round to the closest power of 2 sounds reasonable, and if equidistant then round down.
I'll also let Maria chime in when she's back next ween.
Then we can update explainer.

**Comment by mariakhomenko** [comment]
Using rounding instead of floor SGTM. 
Can you generate the set of possibilities we will report when using most significant 2-bits? I wonder if that gives us useful distinctions between classes of devices.(e.g. it's not clear to me that separating 48GB from 32GB is really that critical)

**Comment by spanicker** [comment]
Rounding is of course error prone, we'll have to look at real data and evaluate if its good enough
We could probably come up with a good threshold from reported values of physical-memory.
How far is it typically from the "right bucket", and refine this based on that.

**Comment by igrigorik** [comment]
Late to the party.. but +1 for closest power of 2.

**Comment by fmeawad** [comment]
After some offline discussions and investigations, we found that: Rounding does solve the issue of having a device with 2000MB of RAM, but does not work very well for devices that have memory closer to 3072 (3GB) which would be reported as 2GB if it was slightly less and 4GB if it was slightly more.
We explored the 2 bits approach more and we found that it would cover those cases better.
2-bits: all binary numbers of the format `(1|11)0*` in MB
Possible device-ram reported values for the 2 bits approach are (in GB):
[0.25, 0.5, 0.75, 1, 1.5, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128]

**Comment by spanicker** [comment]
@igrigorik any concerns?

**Comment by igrigorik** [comment]
sgtm.

**Comment by spanicker** [comment]
Fadi, could you update the first paragraph explaining the 2-bit algorithm here:
https://github.com/WICG/device-ram#the-header
(then we can close this issue)
