### ISSUE TITLE
JavaScript API support

### ISSUE THREAD

**Issue by laukstein** [WICG/device-ram#10]
Please consider Device Memory support also in JavaScript.
`navigator.hardwareConcurrency` doesn't seems returning the memory value,
returns **`8`**  for Intel Core i7 6GB RAM that has

	Cores	4
	Threads	8

**Comment by spanicker** [comment]
Right, the JS API has not been added yet, but we expect it will ship in Chrome M62.
It will be added as navigation.deviceMemory (not hardware concurrency)

**Comment by laukstein** [comment]
Chrome related issue https://bugs.chromium.org/p/chromium/issues/detail?id=758302

**Comment by yoavweiss** [comment]
API [added](https://w3c.github.io/device-memory/#sec-device-memory-js-api). Closing
