### ISSUE TITLE
Setup auto-publish workflow for index.html; deprecate README.md

### ISSUE THREAD

**Issue by igrigorik** [WICG/device-ram#11]
Readme is outdated and does not reflect latest in index.bs.

**Comment by spanicker** [comment]
Philippe is investigating issues with auto publish workflow.

**Comment by spanicker** [comment]
looks like the .bs was bit outdated (not README) I've updated it and corresponding .html

**Comment by spanicker** [comment]
@siusin - could you set this up?

**Comment by siusin** [comment]
Done.

Now the [Editor's Draft](https://w3c.github.io/device-memory/) is auto-generated by the build. Let me know if any problem in your next commit.

**Comment by siusin** [comment]
Btw, if the script works, can we remove `index.html` in the `master` branch and the `device-memory.bs` in the `gh-pages` branch?

**Comment by tidoust** [comment]
Not sure if that's the right issue for auto-publish using spec-prod, but for the sake of linking, note it is still failing, see:
https://github.com/w3c/device-memory/pull/43#issuecomment-876314742

**Comment by plehegar** [comment]
For my own sake:

1. https://github.com/tabatkins/bikeshed/pull/2097 needs to be merged
2. then device-memory GitHub action needs to be rerun
3. then gh-pages needs to be updated again to do the redirect.
4.

**Comment by tidoust** [comment]
> 1. Webperf status 2021 tabatkins/bikeshed#2097 needs to be merged

... and a new version of Bikeshed published to PyPi, as spec-prod uses that version and not the contents of Bikeshed's repo.

Also:

4. Add editor ID, see #45

**Comment by yoavweiss** [comment]
@caribouW3 Seems like ato-publishing [fails](https://github.com/w3c/device-memory/runs/7471322107?check_suite_focus=true) with [you are not authorized to publish](https://labs.w3.org/echidna/api/status?id=b0b72c84-1647-4b1c-85dc-0283bd360ae3) error. Can you take a look?

**Comment by caribouW3** [comment]
@yoavweiss Fixed (apparently the secret echidna token was setup with the wrong value)

**Comment by yoavweiss** [comment]
Thank you!!
