### ISSUE TITLE
Square brackets inside <code> tags are URL encoded for some reason

### ISSUE THREAD

**Issue by jdanford** [WICG/device-ram#17]
`<code>[device-memory]</code>` is being rendered as `%5Bdevice-memory%5D`

### Screenshot:
<img width="804" alt="screen shot 2017-11-02 at 9 25 38 pm" src="https://user-images.githubusercontent.com/5767112/32360579-8cf64a88-c014-11e7-92ef-095ee3e88567.png">

**Comment by plehegar** [comment]
https://w3c.github.io/device-memory/ and https://www.w3.org/device-memory/ seem fine now.
