### ISSUE TITLE
Implementing this RFC is harmful

### ISSUE THREAD

**Issue by KOLANICH** [WICG/device-ram#20]
I think it's better not to implement this spec. Amount of ram is a fingerprinting vector. And permissions are not a solution: everyone knows that _ordinary_ people - the majority of people - never care about privacy. So websites makers will be able to blackmail internet users "either you enable this header, or you don't get the service", and the most of users will agree, because they need privacy less than the service. So implementing this proposal would transform the web into a more unfriendly environment. I wanna browser makers to think ten times before implementing this proposal in their software.

**Comment by detj** [comment]
Indeed & I agree. I'm guessing this API won't be behind a permission gate which makes it even more prone to fingerprinting.

**Comment by igrigorik** [comment]
Hi folks. Apologies, missed this earlier.

> Amount of ram is a fingerprinting vector.

There was a robust discussion and review on this when the proposal was put together and during the intent to ship progress. You can see [some of the notes here](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/MFBsNZCkotU/jYlyh79xAgAJ;context-place=topic/blink-dev/CvheM4B71Ws).

> So websites makers will be able to blackmail internet users "either you enable this header, or you don't get the service".

There is no user opt-in for this. The data is exposed via JS API and via CH opt-in. Full spec @ https://w3c.github.io/device-memory/

Resolving this, but feel free to reopen if earlier discussions do not address your concerns.
