### ISSUE TITLE
IANA considerations section needed

### ISSUE THREAD

**Issue by dret** [WICG/device-ram#21]
since this spec is defining a new HTTP header field, it should have an IANA considerations section, which registers the defined with IANA in the header field registry.

**Comment by dret** [comment]
on second reading, it seems that this spec actually defined two things, a client hint as well as a header field. both of them need to be part of the IANA considerations section.

**Comment by dret** [comment]
hmmm... reading @igrigorik latest client hint spec it seems that client hints are not registered themselves. instead they just refer to HTTP header fields, if i understand the model correctly. in that case, the spec discussed here only defines the HTTP header field, which then gets used as a client hint. but for that header field, an IANA registration is required.

**Comment by igrigorik** [comment]
> the spec discussed here only defines the HTTP header field, which then gets used as a client hint. 

Yep.

> but for that header field, an IANA registration is required.

Open to your guidance on what the right requirements here are. Adding IANA registration for Device-Memory field in the spec makes sense.

**Comment by dret** [comment]
>     the spec discussed here only defines the HTTP header field, which
>     then gets used as a client hint.
> 
> Yep.
> 
>     but for that header field, an IANA registration is required.
> 
> Open to your guidance on what the right requirements here are. Adding 
> IANA registration for Device-Memory field in the spec makes sense.

it seems to me that this is a new header field and not one referred to 
from anywhere else. in that case, it needs a proper definition and needs 
to be registered.
