### ISSUE TITLE
Upper and lower bound should be UA opiniated decision, in entire text.

### ISSUE THREAD

**Issue by GrosSacASac** [WICG/device-ram#23]
The text is inconsistent.
First there is a note :

> NOTE: While implementations may choose different values, the recommended upper bound is 8GiB and the recommended lower bound is 0.25GiB (or 256MiB).

Then the word `is`  is used:

> A full list of possible values is as follows: 0.25, 0.5, 1, 2, 4, 8

To make it consistent use a sentence like 

A full list of possible values should be as follows: 0.25, 0.5, 1, 2, 4, 8

**Comment by GrosSacASac** [comment]
https://w3c.github.io/device-memory/#sec-device-memory-client-hint-header
https://w3c.github.io/device-memory/#examples

**Comment by yoavweiss** [comment]
Closed by https://github.com/w3c/device-memory/pull/46
