### ISSUE TITLE
Deploy failed on later push to master

### ISSUE THREAD

**Issue by foolip** [WICG/device-ram#26]
After https://github.com/w3c/device-memory/pull/25 was merged, the deploy failed on Travis: https://github.com/w3c/device-memory/runs/406165139

The push to master before that didn't fail, so something seems to have changed.

**Comment by plehegar** [comment]
https://travis-ci.com/w3c/device-memory/builds/149241783 passed. Thank you @yoavweiss

**Comment by yoavweiss** [comment]
The deploy passed, but Bikeshed seems to be failing... I'll take a look

**Comment by stephenmcgruer** [comment]
I think that things are still not being pushed, right? https://w3c.github.io/device-memory/#sec-device-memory-js-api still shows as a `NoInterfaceObject` despite https://github.com/w3c/device-memory/pull/25 having landed months ago now.

**Comment by yoavweiss** [comment]
Should be fixed now (changed deploy keys, as the old ones seemed busted...)
