### ISSUE TITLE
Make it clearer that this is part of the client-hints family

### ISSUE THREAD

**Issue by domenic** [WICG/device-ram#3]
This only became apparent when I got to "When is the header sent?"

I think framing it as part of the existing client-hints mechanism makes it seem like a nice extension of an exiting thing instead of something completely new. The latter is sometimes more scary for people.

**Comment by spanicker** [comment]
Good point.
I've made this much more explicit.
The proposal section now starts with:
"We propose a new HTTP Client Hints header and a web exposed API ...."

PTAL?

**Comment by domenic** [comment]
Looks great, thanks!
