### ISSUE TITLE
Drop/Adjust link to ED?

### ISSUE THREAD

**Issue by tidoust** [WICG/device-ram#44]
Once auto-publish has been fixed, the /TR version will always be in sync with the ED. This allows to do #42, meaning to drop the ED altogether.

The /TR version of the spec still has a link to the ED though... which becomes a link to itself. This is at best confusing.

Now, dropping the link entirely may also be confusing for those who are used to "/TR versions are often outdated, always look at the ED". It may be useful to replace the link with an indication that the document always reflects the contents of the repository.

**Comment by yoavweiss** [comment]
Closed by https://github.com/w3c/device-memory/pull/46
