### ISSUE TITLE
Bikeshed: RAM vs. memory

### ISSUE THREAD

**Issue by domenic** [WICG/device-ram#6]
RAM ties us to a specific technology, albeit one that hasn't changed in many years. Memory might be a bit more hardware-architecture agnostic.

**Comment by spanicker** [comment]
are you suggesting naming the header and JS API to memory i.e. device-memory vs. device-ram ?
This API is not really intended as a signal for memory, but rather is a proxy for device class.
(We have other proposals for memory eg. [memory pressure](https://groups.google.com/a/chromium.org/d/msg/blink-dev/kphhS7AnFig/uaJ3kjHfDgAJ), which are on hold at the moment)

**Comment by domenic** [comment]
> are you suggesting naming the header and JS API to memory i.e. device-memory vs. device-ram ?

Yes.

> This API is not really intended as a signal for memory, but rather is a proxy for device class.

I don't really understand this. Is the direction then that it should be named `device-memory-as-a-signal-for-device-class`? Or it should stop returning the amount of memory in the device, and start returning a class? I thought the readme specifically gave reasons why that wasn't a good idea.

> (We have other proposals for memory eg. [memory pressure](https://groups.google.com/a/chromium.org/d/msg/blink-dev/kphhS7AnFig/uaJ3kjHfDgAJ), which are on hold at the moment)

My understanding is that those are related to free memory/RAM, but not to the device's memory/RAM in general, which this API is about.

**Comment by spanicker** [comment]
Sorry I meant that memory has a connotation of "available memory", whereas RAM is a more explicit here as a static value for the device that doesn't change.
+Some more folks to weigh in: @fmeawad @mariakhomenko @igrigorik @yoavweiss

**Comment by domenic** [comment]
Oh, hmm, I don't agree at all. They seem synonymous to me. Free RAM is just as common as free memory. Saying a device has a lot of memory means the same as saying it has a lot of RAM.

**Comment by spanicker** [comment]
If there is consensus on "device-memory" - that SGTM :)
Thoughts - anyone else?

**Comment by igrigorik** [comment]
tomayto, tomahto... :-)

Either works for me, only advantage I can think of for "RAM" is that it's shorter and saves us a few request header bytes, but I won't lose any sleep either way.

Continuing the bikeshed: do we need the "device-" prefix, especially for the header? I'd vote for "RAM: <val>" or "Memory: <val>"... We don't prefix any other values in CH with 'device', which is implicit.

**Comment by spanicker** [comment]
let's go with "memory":
header: s/device-ram/memory/
API: s/navigator.deviceRAM/navigator.memory

**Comment by spanicker** [comment]
I updated the explainer. Do we need to update the repo name?

**Comment by domenic** [comment]
Yeah, you should, as it will change the eventual spec URL.

**Comment by spanicker** [comment]
How about renaming repo to "device-memory", 
claiming "memory" as the repo name for this seems bit strange.

**Comment by spanicker** [comment]
I'd like to revisit this.
Just "Memory" is ambiguous - as it could be interpreted as Available Memory OR Total Memory etc.
Can we change this to "Device Memory" OR "Total Memory" ?

**Comment by fmeawad** [comment]
I like that suggestion, I slightly prefer Device Memory but fine with both.

**Comment by igrigorik** [comment]
Device Memory sgtm.
