### ISSUE TITLE
Header syntax in spec

### ISSUE THREAD

**Issue by domenic** [WICG/device-ram#7]
In https://github.com/WICG/device-ram/blob/master/device-memory.bs we have

```
memory = 1*DIGIT
```

However `.` is not a digit, so `0.5` is not a valid value for the header, according to this grammar.

I think you want something more like http://httpwg.org/http-extensions/client-hints.html#dpr

It looks like you also want to include a boilerplate sentence

> If memory occurs in a message more than once, the last value overrides all previous occurrences.

**Comment by spanicker** [comment]
Thanks! Updated the .bs file
