### ISSUE TITLE
Spec's "this version" link is broken

### ISSUE THREAD

**Issue by RByers** [WICG/device-ram#8]
Viewing the spec via [rawgit.com](https://rawgit.com/WICG/device-ram/master/device-memory.html) it has a link to `https://wicg.github.io/device-memory/` that doesn't work.  I think you just want to create a `gh-pages` branch, make it your default branch, then delete the `master` branch.  That should fix it all.

**Comment by plehegar** [comment]
The spec is now at https://w3c.github.io/device-memory/ and This Version reflects that.
